;; Define prefixes
(global-set-key (kbd "C-q") nil)
(global-set-key (kbd "M-q") nil)

;; Define basic keybindings
(global-set-key (kbd "M-g") 'goto-line)
(global-set-key (kbd "M-<up>") 'beginning-of-buffer)
(global-set-key (kbd "M-<down>")'end-of-buffer)
(global-set-key [(meta shift right)] 'ido-switch-buffer)
(global-set-key [(meta shift left)] 'magit-status)
(global-set-key (kbd "M-c") 'cleanup-buffer)
(global-set-key (kbd "C-S-d") 'backward-delete-char)

;; Rinari keybindings
(global-set-key (kbd "C-q c") 'rinari-console)
(global-set-key (kbd "C-q e") 'rinari-insert-erb-skeleton)
(global-set-key (kbd "C-q f c") 'rinari-find-controller)
(global-set-key (kbd "C-q f e") 'rinari-find-environment)
(global-set-key (kbd "C-q f f") 'rinari-find-file-in-project)
(global-set-key (kbd "C-q f h") 'rinari-find-helper)
(global-set-key (kbd "C-q f i") 'rinari-find-migration)
(global-set-key (kbd "C-q f j") 'rinari-find-javascript)
(global-set-key (kbd "C-q f l") 'rinari-find-plugin)
(global-set-key (kbd "C-q f m") 'rinari-find-model)
(global-set-key (kbd "C-q f n") 'rinari-find-configuration)
(global-set-key (kbd "C-q f o") 'rinari-find-log)
(global-set-key (kbd "C-q f p") 'rinari-find-public)
(global-set-key (kbd "C-q f t") 'rinari-find-test)
(global-set-key (kbd "C-q f s") 'rinari-find-script)
(global-set-key (kbd "C-q f v") 'rinari-find-view)
(global-set-key (kbd "C-q f w") 'rinari-find-worker)
(global-set-key (kbd "C-q f x") 'rinari-find-fixture)
(global-set-key (kbd "C-q f y") 'rinari-find-stylesheet)
(global-set-key (kbd "C-q s") 'rinari-rgrep)
(global-set-key (kbd "C-q g") 'rinari-generate)
(global-set-key (kbd "C-q r") 'rinari-rake)
(global-set-key (kbd "C-q q") 'rinari-sql)
(global-set-key (kbd "C-q t") 'rinari-test)
(global-set-key (kbd "C-q x") 'rinari-extract-partial)

;; Function keybindings
(global-set-key [f5] 'whitespace-mode)
(global-set-key [f6] 'split-window-horizontally)
(global-set-key [f7] 'split-window-vertically)
(global-set-key [f8] 'delete-window)
(global-set-key [f11] 'toggle-fullscreen)
(global-set-key [f12] 'toggle-line-numbers-display)

(provide 'hector/keyboard)
